import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Counter from './components/Counter'
import AllCounter from './components/AllCounter'
import Reloj from './components/Reloj'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
      <AllCounter></AllCounter>

      {/* <Reloj></Reloj> */}
      </main>
    </>
  )
}
